-- Fase 1: Konsolidasi schema modul hukum (PostgreSQL)
-- Jalankan setelah tabel users dan periode_kepengurusan tersedia.

CREATE TABLE IF NOT EXISTS hukum_dokumen (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periode_id INTEGER NOT NULL REFERENCES periode_kepengurusan(id) ON DELETE RESTRICT,
  jenis VARCHAR(20) NOT NULL CHECK (jenis IN ('AD','ART','GBHO','GBMO','PERATURAN','KEPUTUSAN')),
  lingkup VARCHAR(20) NOT NULL DEFAULT 'induk' CHECK (lingkup IN ('induk','BEM','BPM','UKM')),
  nama_ormawa VARCHAR(100),
  judul VARCHAR(500) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  deskripsi TEXT,
  format_mukadimah VARCHAR(10) NOT NULL DEFAULT 'json' CHECK (format_mukadimah IN ('legacy','json')),
  mukadimah_json JSONB,
  mukadimah_legacy TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','aktif','diarsipkan')),
  dibuat_oleh INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  diperbarui_oleh INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_hukum_dokumen_periode_status ON hukum_dokumen (periode_id, status);

CREATE TABLE IF NOT EXISTS hukum_bab (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dokumen_id INTEGER NOT NULL REFERENCES hukum_dokumen(id) ON DELETE CASCADE,
  nomor_label VARCHAR(50) NOT NULL,
  judul_bab VARCHAR(255) NOT NULL,
  bagian_label VARCHAR(255),
  urutan INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (dokumen_id, urutan)
);

CREATE TABLE IF NOT EXISTS hukum_pasal (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dokumen_id INTEGER NOT NULL REFERENCES hukum_dokumen(id) ON DELETE CASCADE,
  bab_id INTEGER REFERENCES hukum_bab(id) ON DELETE SET NULL,
  nomor_label VARCHAR(50) NOT NULL,
  judul_pasal VARCHAR(255),
  urutan INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (dokumen_id, nomor_label),
  UNIQUE (dokumen_id, urutan)
);
CREATE INDEX IF NOT EXISTS idx_hukum_pasal_bab ON hukum_pasal (bab_id);

CREATE TABLE IF NOT EXISTS hukum_workspace (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dokumen_id INTEGER NOT NULL REFERENCES hukum_dokumen(id) ON DELETE CASCADE,
  judul_perubahan VARCHAR(255) NOT NULL,
  tujuan TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif','diajukan','siap_commit','committed','ditutup','dibatalkan')),
  dibuat_oleh INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP,
  closed_by INTEGER REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_hukum_workspace_dokumen_status ON hukum_workspace (dokumen_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_hukum_workspace_active_slot
  ON hukum_workspace (dokumen_id)
  WHERE status IN ('aktif', 'diajukan', 'siap_commit');

CREATE TABLE IF NOT EXISTS hukum_pasal_versi (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pasal_id INTEGER NOT NULL REFERENCES hukum_pasal(id) ON DELETE CASCADE,
  workspace_id INTEGER NOT NULL REFERENCES hukum_workspace(id) ON DELETE CASCADE,
  isi JSONB NOT NULL,
  hash_konten CHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','staged','committed','replaced','rejected')),
  dibuat_oleh INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  dibuat_dari_versi_id INTEGER REFERENCES hukum_pasal_versi(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rejected_at TIMESTAMP,
  rejected_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  rejection_reason TEXT,
  UNIQUE (pasal_id, hash_konten)
);
CREATE INDEX IF NOT EXISTS idx_hukum_versi_pasal_status ON hukum_pasal_versi (pasal_id, status);

CREATE TABLE IF NOT EXISTS hukum_staging (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL REFERENCES hukum_workspace(id) ON DELETE CASCADE,
  status VARCHAR(25) NOT NULL DEFAULT 'menunggu_review' CHECK (status IN ('menunggu_review','disetujui','ditolak','dibatalkan')),
  diajukan_oleh INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  diajukan_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  direview_oleh INTEGER REFERENCES users(id) ON DELETE SET NULL,
  direview_at TIMESTAMP,
  review_note TEXT
);
CREATE INDEX IF NOT EXISTS idx_hukum_staging_workspace_status ON hukum_staging (workspace_id, status);

CREATE TABLE IF NOT EXISTS hukum_staging_versi (
  staging_id INTEGER NOT NULL REFERENCES hukum_staging(id) ON DELETE CASCADE,
  pasal_versi_id INTEGER NOT NULL REFERENCES hukum_pasal_versi(id) ON DELETE RESTRICT,
  PRIMARY KEY (staging_id, pasal_versi_id)
);

CREATE TABLE IF NOT EXISTS hukum_commit (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dokumen_id INTEGER NOT NULL REFERENCES hukum_dokumen(id) ON DELETE RESTRICT,
  staging_id INTEGER NOT NULL REFERENCES hukum_staging(id) ON DELETE RESTRICT,
  parent_commit_id INTEGER REFERENCES hukum_commit(id) ON DELETE SET NULL,
  hash_commit CHAR(64) NOT NULL UNIQUE,
  snapshot_tree JSONB NOT NULL,
  forum_tipe VARCHAR(50) NOT NULL,
  tanggal_forum DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif','digantikan','gagal')),
  dibuat_oleh INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  replaced_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_hukum_commit_dokumen_status ON hukum_commit (dokumen_id, status);

CREATE TABLE IF NOT EXISTS hukum_commit_approval (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commit_id INTEGER NOT NULL REFERENCES hukum_commit(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  role VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'menunggu' CHECK (status IN ('menunggu','disetujui','ditolak')),
  approved_at TIMESTAMP,
  rejected_at TIMESTAMP,
  note TEXT,
  UNIQUE (commit_id, user_id)
);

CREATE TABLE IF NOT EXISTS hukum_relasi_pasal (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pasal_anak_id INTEGER NOT NULL REFERENCES hukum_pasal(id) ON DELETE CASCADE,
  pasal_induk_id INTEGER NOT NULL REFERENCES hukum_pasal(id) ON DELETE CASCADE,
  jenis_relasi VARCHAR(20) NOT NULL DEFAULT 'mengacu' CHECK (jenis_relasi IN ('mengacu','berhubungan','induk_anak')),
  dibuat_oleh VARCHAR(10) NOT NULL DEFAULT 'manual' CHECK (dibuat_oleh IN ('auto','manual')),
  dibuat_oleh_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (pasal_anak_id, pasal_induk_id, jenis_relasi),
  CHECK (pasal_anak_id <> pasal_induk_id)
);

CREATE TABLE IF NOT EXISTS hukum_notifikasi (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relasi_id INTEGER NOT NULL REFERENCES hukum_relasi_pasal(id) ON DELETE CASCADE,
  pasal_anak_id INTEGER NOT NULL REFERENCES hukum_pasal(id) ON DELETE CASCADE,
  pasal_induk_id INTEGER NOT NULL REFERENCES hukum_pasal(id) ON DELETE CASCADE,
  dipicu_oleh_versi_id INTEGER NOT NULL REFERENCES hukum_pasal_versi(id) ON DELETE RESTRICT,
  status VARCHAR(30) NOT NULL DEFAULT 'perlu_ditinjau' CHECK (status IN ('perlu_ditinjau','sudah_diselaraskan','diabaikan_dengan_alasan')),
  catatan TEXT,
  diselesaikan_oleh INTEGER REFERENCES users(id) ON DELETE SET NULL,
  diselesaikan_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_hukum_notifikasi_status ON hukum_notifikasi (status);

CREATE TABLE IF NOT EXISTS hukum_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entitas VARCHAR(80) NOT NULL,
  entitas_id BIGINT NOT NULL,
  aksi VARCHAR(50) NOT NULL,
  aktor_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  sebelum_json JSONB,
  sesudah_json JSONB,
  ip_address INET,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_hukum_audit_entitas ON hukum_audit_log (entitas, entitas_id);

CREATE TABLE IF NOT EXISTS hukum_referensi_inline (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pasal_asal_id INTEGER NOT NULL REFERENCES hukum_pasal(id) ON DELETE CASCADE,
  dokumen_tujuan_id INTEGER NOT NULL REFERENCES hukum_dokumen(id) ON DELETE CASCADE,
  pasal_tujuan_nomor VARCHAR(50) NOT NULL,
  ayat_tujuan_nomor INTEGER,
  konteks_field VARCHAR(50) NOT NULL DEFAULT 'teks_utama',
  status_validasi VARCHAR(20) NOT NULL DEFAULT 'valid' CHECK (status_validasi IN ('valid','dicabut','tidak_ditemukan')),
  terakhir_divalidasi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (pasal_asal_id, dokumen_tujuan_id, pasal_tujuan_nomor, ayat_tujuan_nomor)
);
