<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This migration must be run from CLI.\n");
    exit(1);
}

require_once __DIR__ . '/../../config/database.php';

$pdo = getConnection();
$driver = strtolower((string) DB_CONNECTION);
if (!in_array($driver, ['mysql', 'pgsql'], true)) {
    throw new RuntimeException("Unsupported database driver: {$driver}");
}

function hukumDeletionMigrationHasColumn(PDO $pdo, string $driver, string $table, string $column): bool
{
    $sql = $driver === 'pgsql'
        ? 'SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? AND column_name = ?'
        : 'SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = ? AND column_name = ?';
    $stmt = $pdo->prepare($sql);
    $stmt->execute([$table, $column]);
    return $stmt->fetchColumn() !== false;
}

if (!hukumDeletionMigrationHasColumn($pdo, $driver, 'hukum_graph_snapshot', 'is_active')) {
    $pdo->exec('ALTER TABLE hukum_graph_snapshot ADD COLUMN is_active SMALLINT NOT NULL DEFAULT 1');
}

if ($driver === 'mysql') {
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS hukum_workspace_deletion (
            id BIGINT NOT NULL AUTO_INCREMENT,
            workspace_id INT NOT NULL,
            entity_type ENUM('bab','pasal') NOT NULL,
            entity_id INT NOT NULL,
            base_commit_id INT NOT NULL,
            reason TEXT NOT NULL,
            snapshot_json JSON NOT NULL,
            created_by INT NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            UNIQUE KEY uq_hukum_workspace_deletion_entity (workspace_id, entity_type, entity_id),
            KEY idx_hukum_workspace_deletion_base (base_commit_id),
            CONSTRAINT fk_hukum_workspace_deletion_workspace FOREIGN KEY (workspace_id) REFERENCES hukum_workspace(id) ON DELETE CASCADE,
            CONSTRAINT fk_hukum_workspace_deletion_commit FOREIGN KEY (base_commit_id) REFERENCES hukum_commit(id) ON DELETE RESTRICT,
            CONSTRAINT fk_hukum_workspace_deletion_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci"
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS hukum_staging_deletion (
            id BIGINT NOT NULL AUTO_INCREMENT,
            staging_id INT NOT NULL,
            entity_type ENUM('bab','pasal') NOT NULL,
            entity_id INT NOT NULL,
            base_commit_id INT NOT NULL,
            reason TEXT NOT NULL,
            snapshot_json JSON NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            UNIQUE KEY uq_hukum_staging_deletion_entity (staging_id, entity_type, entity_id),
            KEY idx_hukum_staging_deletion_entity (entity_type, entity_id),
            CONSTRAINT fk_hukum_staging_deletion_staging FOREIGN KEY (staging_id) REFERENCES hukum_staging(id) ON DELETE CASCADE,
            CONSTRAINT fk_hukum_staging_deletion_commit FOREIGN KEY (base_commit_id) REFERENCES hukum_commit(id) ON DELETE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci"
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS hukum_commit_deletion (
            id BIGINT NOT NULL AUTO_INCREMENT,
            commit_id INT NOT NULL,
            entity_type ENUM('bab','pasal') NOT NULL,
            entity_id INT NOT NULL,
            reason TEXT NOT NULL,
            snapshot_json JSON NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            UNIQUE KEY uq_hukum_commit_deletion_entity (commit_id, entity_type, entity_id),
            KEY idx_hukum_commit_deletion_entity (entity_type, entity_id),
            CONSTRAINT fk_hukum_commit_deletion_commit FOREIGN KEY (commit_id) REFERENCES hukum_commit(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci"
    );
} else {
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS hukum_workspace_deletion (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workspace_id INTEGER NOT NULL REFERENCES hukum_workspace(id) ON DELETE CASCADE,
            entity_type VARCHAR(10) NOT NULL CHECK (entity_type IN ('bab','pasal')),
            entity_id INTEGER NOT NULL,
            base_commit_id INTEGER NOT NULL REFERENCES hukum_commit(id) ON DELETE RESTRICT,
            reason TEXT NOT NULL,
            snapshot_json JSONB NOT NULL,
            created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (workspace_id, entity_type, entity_id)
        )"
    );
    $pdo->exec(
        'CREATE INDEX IF NOT EXISTS idx_hukum_workspace_deletion_base ON hukum_workspace_deletion (base_commit_id)'
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS hukum_staging_deletion (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            staging_id INTEGER NOT NULL REFERENCES hukum_staging(id) ON DELETE CASCADE,
            entity_type VARCHAR(10) NOT NULL CHECK (entity_type IN ('bab','pasal')),
            entity_id INTEGER NOT NULL,
            base_commit_id INTEGER NOT NULL REFERENCES hukum_commit(id) ON DELETE RESTRICT,
            reason TEXT NOT NULL,
            snapshot_json JSONB NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (staging_id, entity_type, entity_id)
        )"
    );
    $pdo->exec(
        'CREATE INDEX IF NOT EXISTS idx_hukum_staging_deletion_entity ON hukum_staging_deletion (entity_type, entity_id)'
    );
    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS hukum_commit_deletion (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            commit_id INTEGER NOT NULL REFERENCES hukum_commit(id) ON DELETE CASCADE,
            entity_type VARCHAR(10) NOT NULL CHECK (entity_type IN ('bab','pasal')),
            entity_id INTEGER NOT NULL,
            reason TEXT NOT NULL,
            snapshot_json JSONB NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (commit_id, entity_type, entity_id)
        )"
    );
    $pdo->exec(
        'CREATE INDEX IF NOT EXISTS idx_hukum_commit_deletion_entity ON hukum_commit_deletion (entity_type, entity_id)'
    );
}

echo "Hukum staging deletion schema is ready.\n";
